version: '3.8'

services:
  api:
    build: .
    container_name: keye-poc-api
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/health\"); print(\"ok\")' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
